### ISSUE TITLE
AttributeError: 'LCD' object has no attribute 'temp'

### ISSUE THREAD

**Issue by Blacx** [Bhavithiran97/LCM1602-14_LCD_Library#1]
Hi @Bhavithiran97 thanks for providing this nice library, but I'm having this issue. Seems it couldn't found 'temp' attribute from LCD for LCD_I2C.py.

`AttributeError: 'LCD' object has no attribute 'temp'`

Many thanks.

**Comment by Bhavithiran97** [comment]
Already merged the pull request for this issue !
