### ISSUE TITLE
Bug in instructions for SPI

### ISSUE THREAD

**Issue by joelburton** [Bhavithiran97/LCM1602-14_LCD_Library#3]
The example in the README for SPI isn't correct; this should be something like:

```
lcd = LCD(sck=18, tx=19, cs=6)
```

(also, these docs use "TX" as the name of the SPI output --- it might be helpful for others following along to indicate this is the same as MOSI)

Thanks for this library! It works great :)

**Comment by Bhavithiran97** [comment]
Thanks for your feedback. README Doc is updated.
