### ISSUE TITLE
OSError: [Errno 5] EIO

### ISSUE THREAD

**Issue by nosoropoped** [Bhavithiran97/LCM1602-14_LCD_Library#5]
Hi @Bhavithiran97 ,  I have some problems, despite the fact that I watched the video, and reread your article several times, a message is displayed in Thonny hello_world_i2c.py:
`Traceback (most recent call last):
  File "<stdin>", line 31, in <module>

  File "/lib/LCD_I2C.py", line 53, in __init__

  File "/lib/LCD_I2C.py", line 103, in _command

OSError: [Errno 5] EIO`

tried using without library, pasting everything into one file, the problem persists. Tell me where to dig. Thank you

**Comment by Bhavithiran97** [comment]
Which lcd modulw are you using ? 
This library is for 
https://www.cytron.io/p-3v3-i2c-and-spi-1602-serial-character-lcd?tracking=b-py
