### ISSUE TITLE
Backlight control?

### ISSUE THREAD

**Issue by scruss** [Bhavithiran97/LCM1602-14_LCD_Library#6]
Can you confirm that the backlight can't be controlled? I don't see any commands in the datasheet, and the diagram on page suggests that the backlight is connected permanently to Vss and Vdd

datasheet: https://drive.google.com/file/d/1oKD2RR_impLviQ7R5FnXotGfLS-1VgDk/view

**Comment by Bhavithiran97** [comment]
As we tried there the backlight cannot be controlled, don't have any commands for it.
